
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 63
#define YY_END_OF_BUFFER 64
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[376] =
    {   0,
        0,    0,    0,    0,    0,    0,   61,   61,   64,   62,
       47,   48,   48,   20,   57,   49,   18,   62,   14,   24,
        6,   22,    7,   17,   62,    8,    1,    1,   26,   16,
        5,   11,   49,   49,   15,   25,   30,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   12,   62,   23,   52,   51,   51,   56,
       54,   54,   56,   61,   59,   59,   58,   60,   48,   19,
       49,    4,   46,   27,    2,    0,   53,   50,    0,    2,
        0,    0,    0,    1,    1,    0,   28,   13,    9,   10,
       29,   49,   49,   49,   49,   49,   49,   49,   49,   49,

       49,   49,   49,   49,   46,   49,   49,   49,   49,   49,
       49,   49,   49,   36,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   21,   51,   54,   55,   61,    0,   59,
       60,    0,    2,    0,    0,    0,    0,    2,    0,    2,
        2,    1,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   46,   49,   49,   49,   37,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,    0,

        2,    2,    0,    0,    2,    0,    0,    2,    0,    2,
        0,    0,    0,    2,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   35,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
        3,   44,   49,   49,    0,    2,    0,    0,    2,    0,
        2,    0,    2,    0,    2,    2,    2,   49,   49,   49,
       49,   49,   49,   32,   49,   49,   49,   49,   46,   49,
       49,   49,   49,   49,   49,   49,   49,   49,   49,   49,
       49,   49,   49,   46,   49,   49,   45,    2,    2,    0,

        2,    0,    2,    0,    0,    2,   49,   43,   46,   49,
       49,   49,   49,   34,   49,   49,   49,   49,   49,   49,
       49,   49,   40,   41,   42,   49,   49,   49,   49,   33,
        2,    2,   46,    0,   49,   31,   49,   49,   49,   49,
       49,   49,   49,   49,   49,    0,    0,   49,   49,   49,
       49,   49,   49,    0,    0,   49,   49,   49,    0,    0,
       49,    0,    0,   49,    0,    0,    0,    0,    0,    0,
        0,    0,   39,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   44,   51,   52,   53,   54,   55,   56,   57,
       58,   59,   60,   61,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[63] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    3,    4,    1,
        1,    1,    1,    1,    5,    1,    5,    1,    1,    6,
        6,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    6,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    6,    6,    4,    4,
        4,    4,    4,    6,    4,    4,    4,    4,    4,    5,
        1,    5
    } ;

static const flex_int16_t yy_base[386] =
    {   0,
        0,    0,   60,   61,   64,   65,   68,   69,  758,  759,
      759,  759,  754,  732,  759,    0,  759,  744,  759,  759,
      759,  739,  759,   58,   60,   68,   99,   64,  759,   65,
      729,   66,  704,   39,  759,  759,  759,   50,   45,   66,
       56,   65,   75,  702,   83,  701,   90,   81,  710,   98,
       85,  699,  705,  759,  685,  759,  759,  759,  742,  759,
      759,  741,  724,  711,  759,  738,  759,  126,  759,  759,
        0,  759,  759,  759,  172,  701,  759,  759,  122,  142,
        0,  150,  167,  718,    0,  176,  759,  759,  759,  759,
      759,  685,  686,  684,  683,  682,  684,  693,  678,   96,

      695,  694,  680,  687,  672,  673,  670,  670,  674,  668,
      663,  657,  649,    0,  647,  120,  648,  640,  616,  624,
      632,  115,  632,  614,  617,   58,  614,  620,  614,  117,
      150,  140,  618,  759,  759,  759,  759,  629,  197,  759,
      759,  174,    0,  192,  223,  609,  182,  278,  232,  333,
      246,  635,  616,  611,  600,  599,  612,  604,  613,  607,
      605,  606,  591,  588,  164,  604,  602,  598,  589,  594,
      577,  592,  590,    0,  574,  176,  567,  578,  573,  570,
      564,  564,  551,  551,  555,  546,  548,  543,  550,  548,
      529,  541,  522,  521,  519,  522,  519,  521,  503,  219,

      388,  267,  505,  241,    0,  289,  221,  314,  248,    0,
      261,  337,  358,  369,  503,  495,  500,  486,  484,  494,
      485,  486,  475,  473,  482,  469,  476,    0,  469,  472,
      463,  453,  463,  448,  463,  445,  439,  458,  457,  452,
      445,  434,  428,  437,  442,  424,  433,  426,  410,  411,
        0,    0,  409,  421,  303,    0,  405,  424,  435,  404,
        0,  453,  456,  239,  511,  500,  521,  415,  410,  402,
      412,  393,  406,    0,  392,  392,  398,  396,  387,  383,
      375,  376,  381,  380,  373,  358,  373,  370,  356,  365,
      348,  358,  347,  342,  345,  343,    0,    0,  532,  341,

      543,  497,    0,  564,  568,  587,  331,    0,  357,  336,
      322,  315,  312,    0,  312,  305,  320,  319,  320,  313,
      311,  294,    0,    0,    0,  306,  295,  300,  287,  759,
        0,  611,  313,  279,  271,    0,  280,  268,  274,  270,
      265,  253,  254,  247,  253,  241,  236,  236,  235,  240,
      236,  230,  219,  229,  202,  199,  206,  176,  182,  200,
      161,  146,  140,  144,  139,  125,  127,  102,   93,   80,
       61,   51,  759,  759,  759,  673,  679,  685,  688,  694,
      700,  704,  708,  712,  716
    } ;

static const flex_int16_t yy_def[386] =
    {   0,
      375,    1,  376,  376,  377,  377,  378,  378,  375,  375,
      375,  375,  375,  375,  375,  379,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,   27,  375,  375,
      375,  375,  379,  379,  375,  375,  375,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  380,  375,  375,  375,  381,  375,  375,
      379,  375,  375,  375,  375,  375,  375,  375,  382,  375,
       27,  375,  375,   28,   28,  375,  375,  375,  375,  375,
      375,  379,  379,  379,  379,  379,  379,  379,  379,  379,

      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  375,  375,  375,  375,  380,  375,  375,
      375,  383,   75,  375,  375,  375,  375,  375,  375,  375,
      375,   28,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  375,

      375,  375,  375,  384,  148,  375,  375,  375,  385,  150,
      375,  375,  375,  375,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  201,  201,  375,  375,  375,  375,
      148,  375,  375,  375,  375,  375,  375,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  201,  375,  375,

      375,  265,  265,  375,  375,  375,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  379,  379,  379,  379,  375,
      265,  375,  379,  375,  379,  379,  379,  379,  379,  379,
      379,  379,  379,  379,  379,  375,  375,  379,  379,  379,
      379,  379,  379,  375,  375,  379,  379,  379,  375,  375,
      379,  375,  375,  379,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,    0,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375
    } ;

static const flex_int16_t yy_nxt[822] =
    {   0,
       10,   11,   12,   11,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   16,   16,   33,   34,   35,
       10,   36,   37,   16,   38,   39,   40,   41,   42,   43,
       44,   16,   45,   16,   16,   46,   16,   47,   16,   48,
       49,   50,   51,   16,   52,   53,   16,   16,   16,   54,
       55,   56,   58,   58,   59,   59,   61,   61,   62,   62,
       65,   65,   66,   66,   73,   67,   67,   63,   63,   75,
       75,   77,   74,   84,   85,   95,   78,   87,   88,   90,
       91,   93,  188,   97,  104,   98,   94,   86,   68,   68,

      100,   96,   99,  374,  105,   76,   79,  101,  189,  109,
      106,  102,  107,  373,  103,  121,   80,  110,   81,   81,
      111,  108,  114,  112,  118,   82,  130,  372,  119,  115,
      116,  122,   83,  138,  123,  131,  147,   82,  147,  125,
      371,  148,  148,  120,  370,   83,   83,  161,  162,  149,
      126,  127,   83,  128,  369,  129,  138,  183,   83,  193,
       83,  150,  150,  184,  147,  138,  147,  194,  149,  151,
      151,  177,  178,  138,   83,  368,  138,  367,  138,  142,
      149,  174,  197,   83,  195,  198,   81,   81,  200,  366,
      200,  143,  143,  201,  201,  152,  152,  365,  144,  364,

       83,  151,  151,  196,  138,  145,  200,  174,  200,   86,
      144,  202,  202,   83,   83,  224,  225,  363,  145,  145,
       83,  233,   83,   83,  234,  145,   83,  138,   83,   83,
      145,  145,  362,  145,  361,   83,  138,   83,  202,  202,
      208,  208,  143,  143,  138,  174,  207,  138,  207,  138,
      174,  208,  208,  213,  360,  147,  145,  147,  266,  266,
      205,  205,  264,  359,  264,  214,  214,  265,  265,  145,
      145,  174,  358,  174,  258,  264,  145,  264,  174,  213,
      266,  266,  145,  357,  145,  204,  259,  259,  356,  355,
      354,  174,  213,  213,  353,   80,  206,  205,  205,  213,

      258,  352,  174,  351,   82,  213,  350,  213,  261,  261,
      257,  206,  349,  258,  258,  348,   82,  200,  174,  200,
      258,  262,  206,  174,  206,  206,  258,  347,  258,  375,
      346,  206,  345,  263,  263,  206,  206,  206,  344,  206,
      209,  375,  206,  343,  212,  342,  341,  262,  206,  174,
      206,  174,  210,  210,  340,  339,  210,  210,  338,  211,
      262,  262,  174,  174,  174,  213,  212,  262,  337,  336,
      212,  211,  335,  262,  334,  262,  213,  267,  267,  212,
      212,  333,  330,  212,  212,  329,  212,  328,  214,  214,
      212,  213,  212,  174,  212,  255,  212,  327,  212,  174,

      326,  325,  213,  324,  213,  213,  323,  256,  256,  322,
      321,  213,  257,  320,  144,  213,  213,  213,  174,  213,
      319,  257,  213,  318,  298,  298,  144,  174,  213,  317,
      213,  258,  316,  315,  257,  257,  314,  313,  257,  312,
      311,  257,  258,  299,  299,  174,  310,  257,  309,  257,
      308,  257,  257,  307,  259,  259,  300,  258,  257,  297,
      262,  296,  295,  262,  257,  294,  257,  293,  258,  292,
      258,  258,  301,  301,  174,  263,  263,  258,  291,  290,
      174,  258,  258,  258,  289,  258,  262,  288,  258,  262,
      287,  286,  285,  284,  258,  283,  258,  282,  281,  262,

      262,  280,  262,  262,  304,  174,  262,  305,  279,  262,
      251,  264,  262,  264,  262,  262,  278,  262,  302,  306,
      306,  277,  276,  375,  275,  174,  274,  174,  213,  174,
      303,  303,  273,  305,  272,  375,  271,  211,  270,  258,
      214,  214,  269,  268,  304,  260,  305,  305,  254,  211,
      262,  259,  259,  305,  213,  253,  252,  304,  304,  305,
      251,  305,  263,  263,  304,  258,  250,  213,  213,  249,
      304,  304,  304,  174,  213,  305,  262,  248,  258,  258,
      213,  247,  213,  331,  331,  258,  246,  332,  332,  262,
      262,  258,  245,  258,  305,  244,  262,  304,  243,  242,

      241,  305,  262,  240,  262,  239,  306,  306,  238,  174,
      304,  304,  237,  174,  305,  305,  236,  304,  305,  235,
      305,  305,  174,  304,  232,  304,  231,  305,  230,  305,
      306,  306,  229,  305,  305,  174,  228,  227,  226,  223,
      305,  174,  222,  174,  305,  174,  305,  221,  305,  220,
      219,  218,  217,  216,  215,   84,  203,  305,  305,  139,
      199,  192,  191,  190,  305,  187,  186,  185,  182,  181,
      305,  174,  305,   57,   57,   57,   57,   57,   57,   60,
       60,   60,   60,   60,   60,   64,   64,   64,   64,   64,
       64,   71,  180,   71,  138,  179,  176,  138,  138,  138,

      141,  175,  141,  141,  141,  141,   83,  174,   83,   83,
      145,  173,  145,  145,  206,  172,  206,  206,  212,  171,
      212,  212,  170,  169,  168,  167,  166,  165,  164,  163,
      160,  159,  158,  157,  156,  155,  154,  153,   84,  146,
      140,  139,  137,  136,  135,  134,  133,  132,  124,  117,
      113,   92,   89,   73,   72,   70,   69,  375,    9,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375
    } ;

static const flex_int16_t yy_chk[822] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    3,    4,    5,    6,    5,    6,
        7,    8,    7,    8,   24,    7,    8,    5,    6,   25,
       25,   26,   24,   28,   28,   38,   26,   30,   30,   32,
       32,   34,  126,   39,   41,   39,   34,   28,    7,    8,

       40,   38,   39,  372,   41,   25,   27,   40,  126,   43,
       42,   40,   42,  371,   40,   48,   27,   43,   27,   27,
       43,   42,   45,   43,   47,   27,   51,  370,   47,   45,
       45,   48,   27,   68,   48,   51,   79,   27,   79,   50,
      369,   79,   79,   47,  368,   27,   27,  100,  100,   80,
       50,   50,   27,   50,  367,   50,   68,  122,   27,  130,
       27,   80,   80,  122,   82,   68,   82,  130,   80,   82,
       82,  116,  116,   68,   83,  366,   68,  365,   68,   75,
       80,  364,  132,   86,  131,  132,   83,   83,  142,  363,
      142,   75,   75,  142,  142,   86,   86,  362,   75,  361,

       83,  147,  147,  131,  139,   75,  144,  131,  144,   86,
       75,  144,  144,   83,   83,  165,  165,  360,   75,   75,
       83,  176,   86,   86,  176,   75,   83,  139,   83,   86,
      145,   75,  359,   75,  358,   86,  139,   86,  200,  200,
      207,  207,  145,  145,  139,  357,  149,  139,  149,  139,
      356,  149,  149,  151,  355,  204,  145,  204,  264,  264,
      204,  204,  209,  354,  209,  151,  151,  209,  209,  145,
      145,  353,  352,  351,  202,  211,  145,  211,  350,  151,
      211,  211,  145,  349,  145,  148,  202,  202,  348,  347,
      346,  345,  151,  151,  344,  148,  206,  148,  148,  151,

      202,  343,  342,  341,  148,  151,  340,  151,  206,  206,
      255,  148,  339,  202,  202,  338,  148,  255,  337,  255,
      202,  208,  206,  335,  148,  148,  202,  334,  202,  255,
      333,  148,  329,  208,  208,  206,  206,  148,  328,  148,
      150,  255,  206,  327,  212,  326,  322,  208,  206,  321,
      206,  320,  150,  150,  319,  318,  212,  212,  317,  150,
      208,  208,  316,  315,  313,  213,  150,  208,  312,  311,
      212,  150,  310,  208,  309,  208,  214,  213,  213,  150,
      150,  307,  300,  212,  212,  296,  150,  295,  214,  214,
      212,  213,  150,  294,  150,  201,  212,  293,  212,  292,

      291,  290,  214,  289,  213,  213,  288,  201,  201,  287,
      286,  213,  257,  285,  201,  214,  214,  213,  284,  213,
      283,  201,  214,  282,  257,  257,  201,  281,  214,  280,
      214,  258,  279,  278,  201,  201,  277,  276,  257,  275,
      273,  201,  259,  258,  258,  272,  271,  201,  270,  201,
      269,  257,  257,  268,  259,  259,  260,  258,  257,  254,
      262,  253,  250,  263,  257,  249,  257,  248,  259,  247,
      258,  258,  262,  262,  246,  263,  263,  258,  245,  244,
      243,  259,  259,  258,  242,  258,  262,  241,  259,  263,
      240,  239,  238,  237,  259,  236,  259,  235,  234,  262,

      262,  233,  263,  263,  302,  232,  262,  266,  231,  263,
      230,  302,  262,  302,  262,  263,  229,  263,  265,  266,
      266,  227,  226,  302,  225,  224,  223,  222,  267,  221,
      265,  265,  220,  266,  219,  302,  218,  265,  217,  299,
      267,  267,  216,  215,  265,  203,  266,  266,  199,  265,
      301,  299,  299,  266,  267,  198,  197,  265,  265,  266,
      196,  266,  301,  301,  265,  299,  195,  267,  267,  194,
      265,  304,  265,  193,  267,  305,  301,  192,  299,  299,
      267,  191,  267,  304,  304,  299,  190,  305,  305,  301,
      301,  299,  189,  299,  306,  188,  301,  304,  187,  186,

      185,  305,  301,  184,  301,  183,  306,  306,  182,  181,
      304,  304,  180,  179,  305,  305,  178,  304,  332,  177,
      306,  305,  175,  304,  173,  304,  172,  305,  171,  305,
      332,  332,  170,  306,  306,  169,  168,  167,  166,  164,
      306,  163,  162,  161,  332,  160,  306,  159,  306,  158,
      157,  156,  155,  154,  153,  152,  146,  332,  332,  138,
      133,  129,  128,  127,  332,  125,  124,  123,  121,  120,
      332,  119,  332,  376,  376,  376,  376,  376,  376,  377,
      377,  377,  377,  377,  377,  378,  378,  378,  378,  378,
      378,  379,  118,  379,  380,  117,  115,  380,  380,  380,

      381,  113,  381,  381,  381,  381,  382,  112,  382,  382,
      383,  111,  383,  383,  384,  110,  384,  384,  385,  109,
      385,  385,  108,  107,  106,  105,  104,  103,  102,  101,
       99,   98,   97,   96,   95,   94,   93,   92,   84,   76,
       66,   64,   63,   62,   59,   55,   53,   52,   49,   46,
       44,   33,   31,   22,   18,   14,   13,    9,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,

      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375,  375,  375,  375,  375,  375,  375,  375,  375,  375,
      375
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
    //Diogo Ferreira Sobreira   2018294861
    //Rui Alexandre Coelho Tapadinhas   2018283200
    #include "y.tab.h"
	#include <stdio.h>
	YYSTYPE yylval;
	//int yylex(void);
  	void yyerror(const char* s);


    int line = 1;
    int col = 1;
    int auxLine = 1;
    int auxCol = 1;
    int strlit_error = 0;
	extern int flag_erro;
    int debugMode;
    char * strlit;

#line 768 "lex.yy.c"

#line 770 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define MULTIPLECOMMENT 2
#define STRLIT_ST 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 35 "jucompiler.l"


#line 993 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 376 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 759 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{if(!debugMode)printf("INTLIT(%s)\n",yytext);col+=yyleng; if(debugMode != 1){yylval.intlit = strdup(yytext); return INTLIT;}}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{if(!debugMode)printf("REALLIT(%s)\n",yytext);col+=yyleng; if(debugMode != 1){yylval.reallit = strdup(yytext); return REALLIT;}}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{if(!debugMode)printf("BOOLLIT(%s)\n",yytext);col+=yyleng; if(debugMode != 1){yylval.boollit = strdup(yytext); return BOOLLIT;}}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{if(!debugMode)printf("AND\n");col+=yyleng; if(debugMode != 1)return AND;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{if(!debugMode)printf("ASSIGN\n");col+=yyleng; if(debugMode != 1)return ASSIGN;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{if(!debugMode)printf("STAR\n");col+=yyleng; if(debugMode != 1)return STAR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{if(!debugMode)printf("COMMA\n");col+=yyleng; if(debugMode != 1)return COMMA;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if(!debugMode)printf("DIV\n");col+=yyleng; if(debugMode != 1)return DIV;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{if(!debugMode)printf("EQ\n");col+=yyleng; if(debugMode != 1)return EQ;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{if(!debugMode)printf("GE\n");col+=yyleng; if(debugMode != 1)return GE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{if(!debugMode)printf("GT\n");col+=yyleng; if(debugMode != 1)return GT;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{if(!debugMode)printf("LBRACE\n");col+=yyleng; if(debugMode != 1)return LBRACE;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{if(!debugMode)printf("LE\n");col+=yyleng; if(debugMode != 1)return LE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if(!debugMode)printf("LPAR\n");col+=yyleng; if(debugMode != 1)return LPAR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{if(!debugMode)printf("LSQ\n");col+=yyleng; if(debugMode != 1)return LSQ;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{if(!debugMode)printf("LT\n");col+=yyleng;  if(debugMode != 1)return LT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{if(!debugMode)printf("MINUS\n");col+=yyleng; if(debugMode != 1)return MINUS;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{if(!debugMode)printf("MOD\n");col+=yyleng; if(debugMode != 1)return MOD;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{if(!debugMode)printf("NE\n");col+=yyleng;  if(debugMode != 1)return NE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if(!debugMode)printf("NOT\n");col+=yyleng; if(debugMode != 1)return NOT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{if(!debugMode)printf("OR\n");col+=yyleng; if(debugMode != 1)return OR;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if(!debugMode)printf("PLUS\n");col+=yyleng; if(debugMode != 1)return PLUS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if(!debugMode)printf("RBRACE\n");col+=yyleng; if(debugMode != 1)return RBRACE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if(!debugMode)printf("RPAR\n");col+=yyleng; if(debugMode != 1)return RPAR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if(!debugMode)printf("RSQ\n");col+=yyleng; if(debugMode != 1)return RSQ;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if(!debugMode)printf("SEMICOLON\n");col+=yyleng; if(debugMode != 1)return SEMICOLON;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if(!debugMode)printf("ARROW\n");col+=yyleng; if(debugMode != 1)return ARROW;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(!debugMode)printf("LSHIFT\n");col+=yyleng; if(debugMode != 1)return LSHIFT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if(!debugMode)printf("RSHIFT\n");col+=yyleng; if(debugMode != 1)return RSHIFT;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if(!debugMode)printf("XOR\n");col+=yyleng;  if(debugMode != 1)return XOR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{if(!debugMode)printf("BOOL\n");col+=yyleng; if(debugMode != 1)return BOOL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if(!debugMode)printf("CLASS\n");col+=yyleng; if(debugMode != 1)return CLASS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if(!debugMode)printf("DOTLENGTH\n");col+=yyleng; if(debugMode != 1)return DOTLENGTH;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if(!debugMode)printf("DOUBLE\n");col+=yyleng; if(debugMode != 1)return DOUBLE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if(!debugMode)printf("ELSE\n");col+=yyleng; if(debugMode != 1)return ELSE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if(!debugMode)printf("IF\n");col+=yyleng; if(debugMode != 1)return IF;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if(!debugMode)printf("INT\n");col+=yyleng; if(debugMode != 1)return INT;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if(!debugMode)printf("PRINT\n");col+=yyleng; if(debugMode != 1)return PRINT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if(!debugMode)printf("PARSEINT\n");col+=yyleng; if(debugMode != 1)return PARSEINT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if(!debugMode)printf("PUBLIC\n");col+=yyleng; if(debugMode != 1)return PUBLIC;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if(!debugMode)printf("RETURN\n");col+=yyleng; if(debugMode != 1)return RETURN;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if(!debugMode)printf("STATIC\n");col+=yyleng; if(debugMode != 1)return STATIC;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if(!debugMode)printf("STRING\n");col+=yyleng; if(debugMode != 1)return STRING;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if(!debugMode)printf("VOID\n");col+=yyleng; if(debugMode != 1)return VOID;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if(!debugMode)printf("WHILE\n");col+=yyleng; if(debugMode != 1)return WHILE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if(!debugMode)printf("RESERVED(%s)\n",yytext);col+=yyleng; if(debugMode != 1)return RESERVED;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 90 "jucompiler.l"
{col=1;line++;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if(!debugMode)printf("ID(%s)\n",yytext);col+=yyleng; if(debugMode != 1){yylval.id = strdup(yytext); return ID;}}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{BEGIN COMMENT;col+=yyleng;}
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 98 "jucompiler.l"
{BEGIN 0;col=1;line++;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{BEGIN MULTIPLECOMMENT; auxCol=col; auxLine=line; col+=yyleng;}
	YY_BREAK
case 54:
/* rule 54 can match eol */
YY_RULE_SETUP
#line 102 "jucompiler.l"
{col=1;line++;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{col+=yyleng;BEGIN 0;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(MULTIPLECOMMENT):
#line 105 "jucompiler.l"
{printf("Line %d, col %d: unterminated comment\n", auxLine, auxCol);col+=yyleng;BEGIN 0;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{BEGIN STRLIT_ST; strlit_error = 0; strlit = yytext; col+=yyleng; auxCol=col-1;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{if(!debugMode && !strlit_error)printf("STRLIT(%s)\n",strlit);col+=yyleng; BEGIN 0; if(debugMode != 1){yylval.strlit = strdup(yytext); return STRLIT;}}
	YY_BREAK
case YY_STATE_EOF(STRLIT_ST):
#line 109 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",line,auxCol); col+=yyleng; BEGIN 0;}
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 110 "jucompiler.l"
{col= 1; printf("Line %d, col %d: unterminated string literal\n",line,auxCol); line++; BEGIN 0;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",line,col, yytext); col += yyleng;strlit_error = 1;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", line, col, yytext); col+=yyleng;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 116 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1377 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 376 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 376 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 375);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 116 "jucompiler.l"


int main(int argc, char *argv[]){
    if (argc > 1) {
		if (strcmp(argv[1],"-l") == 0) {
			debugMode = 1;
			yylex();
		}
		else if (strcmp(argv[1],"-t") == 0) {
			debugMode = 2;
			yyparse();
		}
		else if (strcmp(argv[1], "-e1") == 0) {
			debugMode = 0;
			while (yylex() != 0) {
				;
			}
		}
		else if (strcmp(argv[1], "-e2") == 0) {
			debugMode = 0;
			yyparse();
			yylex();
		}
	}
	else {
		debugMode = 0;
		yyparse();
		yylex();
	}
}

int yywrap() {
    return 1;
}

void yyerror (const char* s) { 
	printf ("%s: %s\n", s, yytext);
}
